##### aligning information #####

# The path to the scratch direcotry. Your username will be determined given that you
# can view it with $USER
SCRATCH_DIR:
    "/scratch/alpine"

# The path to your working directory. Leaving this blank will just make it so this full path
# is in your scratch space
BASE_PATH:
    "/pl/active/Anschutz_BDC"
    
# Sample sheet. This is the path to the sample sheet. Should be a tab delimited
# tsv file with the one column titled "sample" and a second column titled
# "fastq1" with filenames relating to each sample. If paired end sequencing was
# done, another columen should be titled "fastq2" with filenames for read 2.
# If spike-ins were included another column can be spike-in with True/False
# values and you must include paths for the COMBINED_GENOME and COMBINED_GTF
SAMPLE_TABLE:
  "files/samples.tsv"

# Project the name of the project
PROJECT:
  "bridget_rnaseq"

# Reference. This should be the path to a directory created using star
GENOME:
  /pl/active/Anschutz_BDC/resources/ref/indices/star/mouse/GRCm38

# Combined genome if spike-ins were used. This should be a path to a combined index using
# star. Can leave blank if no spike-ins were used.
COMBINED_GENOME:

# GTF. This is a path to the gtf file. Should match the genome fa used
GTF:
  /pl/active/Anschutz_BDC/resources/ref/annotation/mouse/GRCm38/gtf/Mus_musculus.GRCm38.96.gtf

# Bed file to use with infer_experiment.py
BED:
  /pl/active/Anschutz_BDC/resources/ref/annotation/mouse/GRCm38/bed/Mus_musculus.GRCm38.96.bed


# Combined gtf if spike-ins were used. Should match the genome fa used.
# Can leave blank if no spike-ins were used.
COMBINED_GTF:

# Path to results directory
RESULTS:
  "results"

# Path to adaptors file. This is included in the bbtools package under .../bbmap/resources/adaptors.fa
# Not necessary if not using bbduk for trimming
ADAPTORS:


# Trim method, can be "bbduk", "cutadapt", or "no"
TRIM_METHOD:
  "cutadapt"

# Parameters for paired end or single end experiments
PE:
    cutadapt:      " -m 20 -a 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCA' -A 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT' "
    salmon:        " --validateMappings --libType 'A' --numBootstraps 50 "
    featureCounts: " --extraAttributes 'gene_name,gene_biotype' -p -B "
    bbduk:         "ktrim=r k=23 mink=11 hdist=1 tpe tbo"


SE:
    cutadapt:      " -m 20 -a 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC' "
    salmon:        " --validateMappings --fldMean 200 --fldSD 20 --libType 'A' --numBootstraps 50 "
    featureCounts: " --extraAttributes 'gene_name,gene_biotype' "
    bbduk:         "ktrim=r k=23 mink=11 hdist=1 tpe tbo"

# Path to where fastq screen references will be saved. If the references have already been
# downloaded they won't be downloaded again
# Alternatively, you can pass the path to a fastq screen config file
FASTQ_SCREEN_DATA:
  "/pl/active/Anschutz_BDC/resources/ref/indices/fastq_screen/FastQ_Screen_Genomes/fastq_screen.conf"
  #"/pl/active/Anschutz_BDC/resources/ref/indices/fastq_screen"


# Path to file containing rmats info. Expects a tsv file with sample, group, and name in the header
# group column must contain `group1` and `group2`. This is used to pull out the groups to be compared
# with rmats
RMATS_INFO:
  "files/rmats_sample_info.tsv"

#################################### Docker images #############################################
GENERAL_CONTAINER:
  "docker/general_docker/rnaseq_general_v3.sif"

R_CONTAINER:
  "docker/r_docker/rnaseq_r_v1.sif"

# Path to fastq_screen container
FASTQ_SCREEN:
  "docker/fastq_screen/fastq_screen_v1.sif"
